export const SHOW_MESSAGE = 'show_message';
export const HIDE_MESSAGE = 'hide_message';
export const FETCH_START = 'fetch_start';
export const FETCH_SUCCESS = 'fetch_success';
export const FETCH_ERROR = 'fetch_error';

// Profile Module
export const GET_PROFILES = 'GET_PROFILES';
export const GET_CONTENTS = 'GET_CONTENTS';
export const DEACTIVATE_PROFILE = 'DEACTIVATE_PROFILE';

export const GET_LIST_USERS = 'GET_LIST_USERS';
export const GET_LIST_USERS_MONETIZE = 'GET_LIST_USERS_MONETIZE';
export const GET_CONTENTS_MONETIZE = 'GET_CONTENTS_MONETIZE';
export const GET_CONTENTS_MONETIZE_META = 'GET_CONTENTS_MONETIZE_META';
export const GET_DASHBOARD_MONETIZE = 'GET_DASHBOARD_MONETIZE';
export const GET_CONTENTS_MONETIZE_CONTENT = 'GET_CONTENTS_MONETIZE_CONTENT';
export const GET_LIST_VOUCHER = 'GET_LIST_VOUCHER';
export const GET_LIST_USERS_VOUCHER = 'GET_LIST_USERS_VOUCHER';
export const POST_CREATE_VOUCHER = 'POST_CREATE_VOUCHER';

export const GET_LIST_USERS_PENGUMUMAN = 'GET_LIST_USERS_PENGUMUMAN';
export const CHANGE_CHECKED_STATE_USERS_PENGUMUMAN = 'CHANGE_CHECKED_STATE_USERS_PENGUMUMAN';
export const TOGGLE_SIDEBAR_COLLAPSED = 'TOGGLE_SIDEBAR_COLLAPSED';
export const GET_CONTACT_COUNTS = 'GET_CONTACT_COUNTS';
export const SET_FILTER_TYPE = 'SET_FILTER_TYPE';
export const ADD_NEW_FAQ = 'ADD_NEW_FAQ';
export const SELECTED_FAQ = 'SELECTED_FAQ';
export const UPDATE_SELECTED_FAQ = 'UPDATE_SELECTED_FAQ';
export const ADD_NEW_INFO = 'ADD_NEW_INFO';
export const SELECTED_INFO = 'SELECTED_INFO';
export const UPDATE_SELECTED_INFO = 'UPDATE_SELECTED_INFO';
